### ISSUE TITLE
Recorded meetings

### ISSUE THREAD

**Issue by mkerollos** [chafey/medical-imaging-community#12]
This community looks really interesting and I'd love to start participating!
Is there any chance your meetings have been recorded or can be recorded going forward? I'm based in Sydney so the 3am timeslot will be hard to attend live.

**Comment by chafey** [comment]
We discussed this as a group and have decided not to record the meetings for a number of reasons.  We do try to publish notes on what was discussed.  We are also exploring ways to hold meetings at a later time so other timezones can participate.

**Comment by mkerollos** [comment]
Thanks Chris - I've been reading the notes, and agree that recording the meetings might change how the discussions happen so I completely respect this decision.
